### ISSUE TITLE
`"7 days ago at 04:00"` only applies the date, not the time

### ISSUE THREAD

**Issue by Schweber** [technologicalMayhem/human-date-parser#5]
Please see [this issue](https://github.com/nushell/nushell/issues/12650) in nushell

**Comment by horasal** [comment]
current grammar only supposes something like `DateTime + Ago` and `at 04:00` is just ignored.

https://github.com/technologicalMayhem/human-date-parser/blob/main/src/date_time.pest#L6

I made a small patch to allow this pattern:

https://github.com/horasal/human-date-parser/commit/6558d68c8c82d4326350466f661232b58ad2bd9c

**Comment by technologicalMayhem** [comment]
This looks good. Mind creating a pull request for it?
